name: CI/CD Pipeline - Build & Deploy on EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Save SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Copy code to EC2
        run: |
          rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no -i key.pem" \
          ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/app

      - name: Build & run on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

            cd /home/ec2-user/app

            docker stop cicd-demo || true
            docker rm cicd-demo || true

            docker build -t cicd-demo:latest .

            docker run -d \
              --name cicd-demo \
              -p 5000:5000 \
              cicd-demo:latest
          EOF
