name: CI/CD with ECR and EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t cicd-demo:latest .
          docker tag cicd-demo:latest ${{ secrets.ECR_REPO }}:latest

      - name: Push image to ECR
        run: |
          docker push ${{ secrets.ECR_REPO }}:latest

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem \
          ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            
            docker pull ${{ secrets.ECR_REPO }}:latest
            
            docker stop cicd-demo || true
            docker rm cicd-demo || true
            
            docker run -d \
              --name cicd-demo \
              -p 5000:5000 \
              ${{ secrets.ECR_REPO }}:latest
          EOF
