name: CI/CD with ECR and EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ğŸ” STEP 1: Create SSH key file
      - name: Create SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      # ğŸ” STEP 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ğŸ” STEP 3: Login to ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ğŸ³ STEP 4: Build & push image
      - name: Build and push Docker image
        run: |
          docker build -t cicd-demo:latest .
          docker tag cicd-demo:latest ${{ secrets.ECR_REPO }}:latest
          docker push ${{ secrets.ECR_REPO }}:latest

      # ğŸš€ STEP 5: Deploy on EC2
      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem \
          ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            
            docker pull ${{ secrets.ECR_REPO }}:latest
            
            docker stop cicd-demo || true
            docker rm cicd-demo || true
            
            docker run -d \
              --name cicd-demo \
              -p 5000:5000 \
              ${{ secrets.ECR_REPO }}:latest
          EOF
